name: Run AIVA Test Batch in a more complex way

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
    inputs:
      LABELS:
        description: "Labels for the tests that should be run, semicolon separated"
        type: string
        default: "" 
      MAX_NUMBER_OF_AGENTS:
        description: "Maximum number of AIVA agents that can be used for running tests"
        type: number
        default: 3
      TEST_NAME:
        description: "(Optional) Name for the test batch"
        type: string
        default: "CI Batch" 
      GLOBAL_OVERRIDES: 
        description: "(Optional) Override variables in all tests. Use JSON format as in an API call."
        type: string
        default: "" 
      OVERRIDES_PER_TEST: 
        description: "(Optional) Override variables in the test specified by test ID. Use JSON format as in an API call."
        type: string
        default: "" 
      GATEWAY_NAME: 
        description: "(Optional) Name of a gateway to use during the batch run"
        type: string
        default: "" 
      POLL_PERIOD:
        description: "(Optional) Specifies how long to wait between API calls for the batch status."
        required: false
        type: number
        default: 10
      REPORT_FILEPATH:
        description: "(Optional) Path to where the CTRF report should be saved."
        required: false
        type: string
        default: "./batch-ctrf.json"

jobs:
  aiva_batch_job:
    name: Run AIVA batch (example)
    runs-on: ubuntu-latest

    steps:
      - name: Start AIVA batch
        id: aiva
        uses: aiva-actions/run@v1
        with:
          apiKey: ${{ secrets.AIVA_APIKEY }}
          labels: ${{ inputs.LABELS || 'pv260,' }}
          maxNumberOfAgents: ${{ inputs.MAX_NUMBER_OF_AGENTS || 3 }}
          testName: ${{ inputs.TEST_NAME || 'CI Batch' }}
          globalVariableOverrides: ${{ inputs.GLOBAL_OVERRIDES || '{"coursename":"CourseName"}' }}
          variableOverridesPerTest: ${{ inputs.OVERRIDES_PER_TEST || '' }}
          gatewayName: ${{ inputs.GATEWAY_NAME || 'doma' }}
          pollPeriodSeconds: ${{ inputs.POLL_PERIOD || 10 }}
          reportFilePath: ${{ inputs.REPORT_FILEPATH || './batch-ctrf.json' }}
    
      - name: Download Summary template
        id: template-download
        run: wget https://raw.githubusercontent.com/aiva-actions/run/refs/heads/main/summary-template.hbs

      - name: Generate CTRF summary
        id: summary
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: '${{ inputs.REPORT_FILEPATH }}'
          template-path: './summary-template.hbs'
        if: always()
